### PR TITLE
Arbitrary enum discriminant

### LINKED ISSUE #6: Allow arbitrary enums
[RFC 2363](https://github.com/rust-lang/rfcs/pull/2363) allows to set custom discriminant on arbitrary enums with payloads, and not just C-like enums.

~~While it's currently a nightly-only feature~~ It's a stable feature since Rust 1.56, it would be great to support arbitrary enums in serde-repr too.

### PR DESCRIPTION
**Pull request by elpiel**
Tries to resolve #6 

I am definitely looking for feedback since macros are not my thing (yet).

This successfully compiles and *serializes* the value of arbitrary enum at the moment, but not the fields themselves.
I think we should call the `Serializer::serialize_*_variant` if I am not mistaken?

This is also quick and dirty, I hope to implement the feature first and then fix `feature` & the `nightly` rust-toolchain

### CODE REVIEW

**Comment by RReverser** [comment]
> This is also quick and dirty, I hope to implement the feature first and then fix `feature` & the `nightly` rust-toolchain

Do you think you're still going to come back to this?

**Comment by elpiel** [comment]
Hey @RReverser , I definitely hope I can come back to this.
The reason I stopped is that I need some feedback as I haven't worked with macros that much and don't actually need it right now, however I am still eager to do it, I just don't know how to proceed

**Comment by RReverser** [comment]
Ah.

One nitpick from my side is that, instead of `as #repr` everywhere, I'd change the last line to `<#repr as serde::Serialize>::serialize(&value, serializer)` instead - this would make code a bit cleaner, while still enforcing serialization of a specific type.

But, since it would be changing the original code too, I guess decision and proper review is best left to @dtolnay.

**Comment by elpiel** [comment]
> > This is also quick and dirty, I hope to implement the feature first and then fix `feature` & the `nightly` rust-toolchain
> 
> Do you think you're still going to come back to this?

I currently don't have the time to work on this and I don't need it at this point.
Anyone is welcome to continue this work, otherwise if I happen to need it in the future I might come back to it

**Review by dtolnay — COMMENTED** [review]
Thanks for the PR!

This is not a feature I am interested in having in this crate, but anyone else should feel free to maintain the functionality as a different crate.

**Pull request closed without merging**
